//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirProduct
    {
        public int Id { get; set; }
        public string FlightCompany { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public string FromPlace { get; set; }
        public string ToPlace { get; set; }
        public int Price { get; set; }
        public Nullable<bool> isBooked { get; set; }
        public Nullable<bool> isSaved { get; set; }
    }
}
